### ISSUE TITLE
Query Parameters on Websocket Endpoint

### ISSUE THREAD

**Issue by sanhardik** [miguelgrinberg/flask-sock#15]
Hello, 
Is it possible to pass query parameters on WS endpoint

For example
```
@sock.route('/echo')
def echo(sock):
    print(f'User: {request.args.get('user')}') 
    while True:
        data = sock.receive()
        sock.send(data)
```

wscat -c http://localhost/echo/?user=123456

When I tried, I get a 404 response

**Comment by miguelgrinberg** [comment]
Remove the slash before the question mark. Note that your route definition does not end in slash.

**Comment by sanhardik** [comment]
Thanks, that was a dumb mistake.
