### ISSUE TITLE
Using sessions

### ISSUE THREAD

**Issue by rickwierenga** [miguelgrinberg/flask-sock#31]
First off, thanks for all of your amazing work.

I am looking to use sessions with flask-sock, and found your tutorial for socketio [here](https://blog.miguelgrinberg.com/post/flask-socketio-and-the-user-session). Unfortunately this does not work with this library (yet). I am willing to create a PR for this, but would appreciate a pointer on where to start.

Here's a minimal reproducible example:

```py
# app.py
from flask import Flask, jsonify, render_template, session
from flask_session import Session
from flask_sock import Sock

app = Flask(__name__, template_folder='.')
app.config["SECRET_KEY"] = "whatever"
app.config['SESSION_TYPE'] = 'filesystem'
sess = Session()
sess.init_app(app)
sock = Sock(app)

@app.route("/")
def index():
  session["index"] = True
  return render_template("index.html")

@sock.route("/ws")
def handle_ws(ws):
  session["ws"] = True
  while True:
    message = ws.receive()
    ws.send(session)

@app.route("/session")
def get_session():
  return jsonify(session)

if __name__ == "__main__":
  app.run(port=5001)
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <script>
      function startWebsocket() {
        var ws = new WebSocket("ws://localhost:5001/ws");
        ws.onopen = function () {
          console.log("Connected to websocket");
          ws.send("Hello, world!");
        };
        ws.onmessage = function (event) {
          console.log("Received message from websocket");
          console.log(event.data);
        };
        ws.onclose = function () {
          console.log("Disconnected from websocket");
        };
      }

      window.onload = startWebsocket;
    </script>
  </body>
</html>
```

Thanks again!

**Comment by miguelgrinberg** [comment]
Are you trying to send the session dictionary as a websocket message? You can only send text or bytes, maybe that is the problem?

**Comment by miguelgrinberg** [comment]
@rickwierenga I don't understand what is the problem. Running your code, the websocket client displays the correct session data:

```
Connected to websocket
Received message from websocket
<FileSystemSession {'_permanent': True, 'index': True, 'ws': True}>
```

And the `/session` endpoint as well:

```
{"_permanent":true,"index":true}
```

If you were expecting the `ws` key to be seen by the `/session` endpoint, that is incorrect. Flask saves the session when a route exits. Your WebSocket route runs a loop and never exits, so the session changes you make in this route will not be saved, unless you save them yourself.

**Comment by rickwierenga** [comment]
> Flask saves the session when a route exits.

Didn't know that, thanks for explaining.
