### ISSUE TITLE
About geventwebsocket

### ISSUE THREAD

**Issue by Mrshenxh** [miguelgrinberg/flask-sock#46]
When I specify geventwebsocket to flask_sock, the websockt interface does not take effect and cannot be connected. I execute the following command:
gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker wsgi:app -c gunicorn.conf.py

Is there a conflict between the two, but if I don't specify geventwebsocket, my socketio interface will report another error。

Please help me！Thanks！

**Comment by miguelgrinberg** [comment]
gevent-websocket is not used or needed for this package to work. See the docs for how to run with gevent.

**Comment by Mrshenxh** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/50947635/218909137-10f8caf7-563d-4378-a95c-523c71f262df.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/50947635/218909458-f242d60c-038f-468d-9b20-852303c1f5af.png">
I know that if I use gevent, I can just specify work-class as gevent. But this conflicts with flask_socketio, doesn't flask_socketio need to specify geventwebsocket?

A command like this: gunicorn -k gevent run:app -c gunicorn.conf.py
If I don't specify geventwebsocket, it will report the following error

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/50947635/218910292-f501394e-97ff-4495-98de-bd73c81f30de.png">

RuntimeError: You need to use the gevent-websocket server. See the Deployment section of the documentation for more information.

So, I'm a little confused, I'd like you to answer it again, thank you very much!!!

**Comment by Mrshenxh** [comment]
If I use this command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker wsgi:app -c gunicorn.conf.py
flask_sock will not work.

**Comment by miguelgrinberg** [comment]
I have not intended for people to use both Flask-SocketIO and Flask-Sock in the same application. Flask-Sock is a newer extension, it is not built to be compatible with the older Flask-SocketIO.

**Comment by Mrshenxh** [comment]
Because I'm using your flask_socketio library for this project, and it's awesome. However, we also need to support websocket in our project, so I want to combine the two into one project. It doesn't matter if it can't.
Ok, I see. Then I'll close the question. Thank you for your answer. It helped me a lot.
