### ISSUE TITLE
Connection always close with 1006

### ISSUE THREAD

**Issue by GiuseppeBocci** [miguelgrinberg/flask-sock#52]
I'm trying to send push notifications to the client after the opening of the connection.

```python
@sock.route('/sock')
def sock(ws):
    id= ws.receive()
    if id_exists(id):
        while condition:
            pass
            line = next_line()
            line = out.readline().strip()
            if line != "":
                ws.send(line)
                sleep(0.2)
            else:
                sleep(2)
        ws.send("pushing finished")
        ws.close(1000, message="FILES_READY")
        return abort(500)
    else:
        ws.close(reason=1008, message="BAD_REQUEST")
```

The client receive all the messages, but the connection always die with 1006 instead of closing and I don't understand why. I'm using it in debug mode.
There is any other way to close the connection without aborting?

**Comment by miguelgrinberg** [comment]
What web server are you using? If you are using Werkzeug, I suggest you try a production web server to see if you get better results.

**Comment by GiuseppeBocci** [comment]
> What web server are you using? If you are using Werkzeug, I suggest you try a production web server to see if you get better results.

Thanks for your quick response. I tried to use the gevent WSGI server, but the result is the same

**Comment by miguelgrinberg** [comment]
Well, I cannot reproduce this here. I'm using the `echo.py` example from this repository, which allows you to type anything in the browser and the server replies back with the same text. If you type `close`, the server ends the websocket connection.

I've added code in the JavaScript side to show `code` value on the close event and I'm getting `1000`, which is the expected. Here is the diff, in case you want to try this example:

```
diff --git a/examples/templates/index.html b/examples/templates/index.html
index 5fecab5..9e42d57 100644
--- a/examples/templates/index.html
+++ b/examples/templates/index.html
@@ -22,7 +22,7 @@
         log('<<< ' + ev.data, 'blue');
       });
       socket.addEventListener('close', ev => {
-        log('<<< closed');
+        log('<<< closed ' + ev.code + ' ' + ev.reason);
       });
       document.getElementById('form').onsubmit = ev => {
         ev.preventDefault();
```

I tested Chrome and Firefox, both return 1000 after I close the connection.

**Comment by GiuseppeBocci** [comment]
Looking at the examples I tried different options.
I almost solved my problem(the connection is closed with the code and message I wanted):
### Using Werkzeug:
I eliminated the `return abort(xxx)` and added a While True. Now, my code look like this:
 ```python
@sock.route('/sock')
def sock(ws):
    while True:  # wrapping while added
        id= ws.receive()
        if id_exists(id):
            while condition:
                pass
                line = next_line()
                line = out.readline().strip()
                if line != "":
                    ws.send(line)
                    sleep(0.2)
                else:
                    sleep(2)
            ws.send("pushing finished")
            ws.close(1000, message="FILES_READY")   # return abort(500) deleted
        else:
            ws.close(reason=1008, message="BAD_REQUEST")
```
for what I can say a `break` it is not necessary. I also tried to modify the echo example with the server closing the connection and it works:
```python
@sock.route('/echo')
def echo(ws):
    while True:
        data = ws.receive()
        if data == 'close':
            ws.close(1000, message="All ok")  # break not needed
        ws.send(data) 
```

❓**Here is my question: "why do I need the `while True` to wrap the function's body?"**

⚠️ Note - In the console the following lines are printed in both the examples:
```
127.0.0.1 - - code 400, message Bad request syntax ('\x88\x8d*%\x8a\x87)ÍÌÎf`ÙØx`ËÃs')
127.0.0.1 - - "None /sock HTTP/0.9" HTTPStatus.BAD_REQUEST -
```

### Using gevent WSGI server:
For me it seems the problem was the monkey patching too late, so I moved it before all the imports, but sometimes the first execution does not work (returned code=1006).
Using the wrapping `while True` seems to always work, but I'm not sure.
⚠️ Note - This error is printed in the console in both cases and in the echo example too :
```
gevent.exceptions.ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent._gevent_c_waiter.Waiter object at 0x0000029C97723458>>
2023-04-13T09:48:07Z <Greenlet at 0x29c9771f1a8: _handle_and_close_when_done(<bound method WSGIServer.handle of <WSGIServer at , <bound method StreamServer.do_close of <WSGIServer, (<gevent._socket3.socket [closed] at 0x29c97716b38)> failed with ConcurrentObjectUseError
```
❓**To your knowledge, does this error alters the run of the program? Is there anything I can do to prevent this error?**

**Comment by GiuseppeBocci** [comment]
>⚠️ Note - In the console the following lines are printed in both the examples:
>Not really sure what code you are running that causes this, and what version of Werkzeug. I do not see these messages here when using the echo example app.

About the first note:
I get this message from the normal example echo app too. My version of Werkzeug is 2.2.2 .


> why do I need the while True to wrap the function's body?

Here I wasn't referring to the echo example. This happens to me:
- if I follow this structure I can end the connection from the server with the code I want.
```python
@sock.route('/foo')
def foo(ws):
    while True:
        pass
        ws.close(reason=code, message="example")
```
- If I use this one, as in the echo example, it ends the connection with the code 1000
```python
@sock.route('/foo')
def foo(ws):
    while True:
        pass
        break   
``` 
- If I don't use a `while True` loop the connection always ends with the code 1006.

>Here you would be closing the socket, and then a ws.send() call will be made. Why would you want to do that? This call will likely end with an error since the socket is now closed. The break is there to gracefully exit the while loop.

For me, the `ws.close()` also breaks from the `while True`, in ALL the past examples.
Given this code:
```python
@sock.route('/echo')
def echo(ws):
    while True:
        data = ws.receive()
        if data == 'close':
            ws.close(1000)
            break
        print("hello1")
        ws.send("hello2")
        ws.send(data)

```
In the page, I get the following output:
![image](https://user-images.githubusercontent.com/61885676/231785454-8997eb6f-923b-44d2-b16d-57fc9992ad5c.png)
In the prompt, I get:
```
127.0.0.1 - - [13/Apr/2023 16:10:26] "GET / HTTP/1.1" 200 -
hello1
hello1
```
with no error other than:
> 127.0.0.1 - - [13/Apr/2023 16:10:36] code 400, message Bad request syntax ('\x88\x820\x18;Þ3ð')
> 127.0.0.1 - - [13/Apr/2023 16:10:36] "None /echo HTTP/0.9" HTTPStatus.BAD_REQUEST -

And I get no error in the javascript console, so I deduced that the `ws.close()` also breaks from the `while True`.

Sorry if I didn't explain the problem well. I hope it's clearer this time, please let me know if any further clarification is needed.

**Comment by miguelgrinberg** [comment]
> I get this message from the normal example echo app too. My version of Werkzeug is 2.2.2 .

Okay, I see the 400 now. Werkzeug 2.0.x does not show it, but 2.1.x and 2.2.x do, so they must have changed something that affects the ending of the WebSocket connection.

> If I don't use a while True loop the connection always ends with the code 1006.

I'm sorry but I still don't understand what you mean here. If you don't use a while loop, how do you prevent the websocket route from exiting? The connection closes when the route function ends so you need something to keep the function running.

> For me, the ws.close() also breaks from the while True, in ALL the past examples.

The `close()` has nothing in it that breaks a loop. It does not even know if it is called inside or outside a loop. What happens is that something that you do after the close call errors due to the socket being closed, and that causes the websocket route to abort. It's a bad practice, and completely unintuitive to rely on this indirect behavior. If you want my advice, I would break the loop gracefully and call close outside the loop at the end.
