### ISSUE TITLE
Support for Type hints

### ISSUE THREAD

**Issue by RandomNameUser** [miguelgrinberg/flask-sock#55]
I'm trying to use flask-sock in an environment that enforces mypy --strict compatibility.

Would it be possible add type hints to the code? Given that type hints have been around since 3.5 in 2015, I'm somewhat skeptical there are many people left that would have a problem with them.

Thanks!

**Comment by miguelgrinberg** [comment]
Honestly I would prefer that someone contributes type hints for this package to [typeshed](https://github.com/python/typeshed). I personally do not rely on type hints or mypy, so maintaining type hints in this (and my many other packages) would add a considerably effort. Consider that the Python standard library uses the same approach, all of its type hints or hosted on the typeshed project.

**Comment by RandomNameUser** [comment]
Agreed. Didn't know about typeshed, thanks for the hint.
