### ISSUE TITLE
Is Flask-Sock binary safe? (are there any escape characters?)

### ISSUE THREAD

**Issue by tschesnok** [miguelgrinberg/flask-sock#61]
I'm having issues with bytes that are larger than 127. Anything using the signed or 8 bit is creating an error the server is returning:

'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte

Probably not your code.. but I just want to get that checked off. :)

**Comment by miguelgrinberg** [comment]
@tschesnok share a complete stack trace please. Without that I have no way to know what this is about.

**Comment by tschesnok** [comment]
I'm not sure how to do that. There are no server side error messages in the console. My server side code simply prints "packet received" on incoming packets. When I send packets from the client (in C++) if one of the bytes is larger than 127 then the server sends back a packet containing the message above with the hex indicating the position of the byte in the buffer that is larger than 127. I also don't get a "packet revived" print in that instance. This may very well be something in our code. I just wanted to hear that bytes above 127 should be fine..

**Comment by miguelgrinberg** [comment]
I think it must be your server that is sending error messages as websocket packets, Flask-Sock does not do that, at least not intentionally.

The WebSocket protocol supports both text and binary messages. Which type if your C++ sending? If it sends text messages, then the text should be encoded in UTF-8. If it sends binary, it can send anything it wants.

**Comment by tschesnok** [comment]
Thank you. I think that may be the clue.. we may be sending binary data while it is expecting UTF-8.
