### ISSUE TITLE
Arch repositories or AUR addition

### ISSUE THREAD

**Issue by MushroomGecko** [miguelgrinberg/flask-sock#69]
Hi! I was wondering if you would be willing to make flask-sock available through the official Arch Linux repositories or through the AUR. This would be an incredible convenience. Thank you for your time!

**Comment by miguelgrinberg** [comment]
No, sorry. I release my packages through the official Python package repository. I do not have the bandwidth to support any other distribution mechanisms.

**Comment by MushroomGecko** [comment]
> No, sorry. I release my packages through the official Python package repository. I do not have the bandwidth to support any other distribution mechanisms.

Ok. Thank you for your response! Have a great day!
