### ISSUE TITLE
Timeouts after 10 mins with error code 1006

### ISSUE THREAD

**Issue by imrankhan17** [miguelgrinberg/flask-sock#7]
I have a flask-sock app deployed using gunicorn and nginx.  I get disconnected after 10 minutes (sometimes sooner) with the following error: `Disconnected (code: 1006, reason: "")`

Is there a way to configure the timeout length?

I'm running it with: `gunicorn --bind 127.0.0.1:5655 --workers 4 --threads 20 wsgi:app`

**Comment by miguelgrinberg** [comment]
This could be the browser closing the socket due to inactivity. The WebSocket protocol has a ping/ping mechanism, but most browsers do not implement it and this server does not either (though I've been considering adding it).

What most people do is just send a dummy message  every 50 seconds or so to keep them from timing out (I believe some browsers timeout sockets at one minute).

**Comment by imrankhan17** [comment]
Thanks for the suggestion.  As it happens I managed to fix the issue with this: https://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed-with-close-code-1006/57706152#57706152

**Comment by miguelgrinberg** [comment]
@imrankhan17 I'm not sure that's the best solution, because making the nginx timeouts longer will (I think) affect your non-websocket routes as well. As I said above, the best to beat timeouts is to have a little interval function in the browser that sends a dummy package regularly.

**Comment by imrankhan17** [comment]
I have a separate nginx config for this websocket route so that shouldn't be an issue.  With your suggestion, do you mean it's the client's responsibility to send dummy messages or can I do the same from the server too?

**Comment by miguelgrinberg** [comment]
It does not matter who sends the package, the only purpose is to keep some traffic in the line to prevent the timeouts. I suggested you do it from the client because it is easier. I was considering adding pings in the server as a definitive solution to this problem.

**Comment by imrankhan17** [comment]
Ok great, I'll look into adding in the pings but it'd be great if you added it into the package too.

**Comment by miguelgrinberg** [comment]
Yes, keeping this issue open so that I don't forget!

**Comment by sanhardik** [comment]
@miguelgrinberg Is this something that you are working on ? 
Would this be a change in simple-websockets code base ?

I was thinking adding an option in initialization for enabling the ping and then checking on time in this [code](https://github.com/miguelgrinberg/simple-websocket/blob/main/src/simple_websocket/ws.py#L117) to send a ping.

**Comment by miguelgrinberg** [comment]
@sanhardik I haven't had time to look at this yet, but yes, doing this in the thread may be the best solution.

**Comment by lawndoc** [comment]
> It does not matter who sends the packet, the only purpose is to keep some traffic in the line to prevent the timeouts. I suggested you do it from the client because it is easier. I was considering adding pings in the server as a definitive solution to this problem.

Does the current websocket Server instantiation support adding `ping_interval` from the config?
```python
                ws = Server(request.environ, **current_app.config.get(
                    'SOCK_SERVER_OPTIONS', {}))
```
Am I reading the code correctly that I just add something like `SOCK_SERVER_OPTIONS = {"ping_interval": 50}` to my app config to enable server ping?
