### ISSUE TITLE
Join/Leave Rooms

### ISSUE THREAD

**Issue by nbyloff** [miguelgrinberg/flask-sock#76]
I've got a web service that will only connect to the wss:// protocol so I can't use [flask-socketio](https://github.com/miguelgrinberg/Flask-SocketIO). This package works perfect, except the one thing I need to do is emit messages to specific users sometimes. Sure enough [you did a demo](https://github.com/miguelgrinberg/Flask-SocketIO-Chat) with a great solution for my issue.

This package doesn't use namespaces, but looking at the [basic_enter_room](https://github.com/miguelgrinberg/python-socketio/blob/7cc84bd13dfa0a86b0326446fb6954949ef948c0/src/socketio/base_manager.py#L104) function, could the same functions for joining/leaving rooms, emitting messages to specific rooms, be added to [this class](https://github.com/miguelgrinberg/simple-websocket/blob/632ec52ce1fce4908b9733e3d24935b2a0514472/src/simple_websocket/ws.py#L248)?

If @miguelgrinberg sees this, is it a heavy lift to add something like this? I don't know how much more there is to managing these connections and rooms, but your rooms solution is perfect for me I just need need the wss:// protocol. 

If preferred, I'd be happy to do a pull request if it's as simple as I make it sound. :)

**Comment by miguelgrinberg** [comment]
I guess it is possible, but this package isn't the right place for such a hight level feature. You can create a separate package that implements rooms on top of it, though.

**Comment by nbyloff** [comment]
Fair enough. This was just the only stable package I could find that supported the wss protocol. I'll roll my own. Thanks!

**Comment by nbyloff** [comment]
> When you complete it maybe link in the comments here. I've seen this come up several times.

Will do. I still think it's worthwhile adding it to this package, especially if others asked for it too. flask-sock is a great compliment to flask-socketio for users who can't use http. I may just add some code to control the messaging in my code instead of an additional package on top of this. Whichever route I go, I'll share.

**Comment by miguelgrinberg** [comment]
@nbyloff you seem to have a misunderstanding of what Flask-SocketIO can or cannot do. You can configure it to work with WebSocket only, with HTTP only, or with both HTTP and WebSocket together.

This package is a simple WebSocket integration. Since the WebSocket protocol does not have a concept of rooms, such a high-level feature does not belong here, regardless of being a useful feature, which I agree that it is.

**Comment by nbyloff** [comment]
> @nbyloff you seem to have a misunderstanding of what Flask-SocketIO can or cannot do. You can configure it to work with WebSocket only, with HTTP only, or with both HTTP and WebSocket together.
> 
> This package is a simple WebSocket integration. Since the WebSocket protocol does not have a concept of rooms, such a high-level feature does not belong here, regardless of being a useful feature, which I agree that it is.

I did misunderstand, thanks for clarifying. I mentioned it specifically several times because I tried to demo a remote service that uses websockets and use socketio. I was told they can't/won't support socketio because the connection wasn't working and I should use this package instead. When I asked them why, I was told it's because the vendor only supports wss:// connections. (I guess the first example they saw was http?) 

This library does work perfectly with their service, but since I've learned from you there's no reason it shouldn't work, I need to look again. And maybe point the vendor to this thread. :)

The whole conversation started with them over this error I was receiving:

````
"The client is using an unsupported version of the [Socket.IO](http://socket.io/) or [Engine.IO](http://engine.io/) protocols (further occurrences of this error will be logged with level INFO)"

# my versions
python-socketio 5.11.1
python-engineio 4.9.0
````

So I don't think it was a version thing. Their client is most likely extremely old and I need to do some debugging on the actual request their client is making. 

Thanks for opening my eyes!

**Comment by miguelgrinberg** [comment]
The problem is that you continue to mix up things that work at different levels. When you say `wss://` all you are saying is that a WebSocket connection is used, but you are not saying what format the data that is exchanged is, which is something that the client and the server must agree on.

If the server is a Socket.IO server, then you need to use a Socket.IO client to connect. If the server is not a Socket.IO server, then you need to figure out what protocol the server speaks, and use a client that is compatible with that.

**Comment by nbyloff** [comment]
That's what I meant about the difference in "handshake". I started with the assumption the clients & servers were interchangeable like browsers and web servers. I know better now. Sorry for the confusion.
